services:
  postgres:
    image: postgres:16-alpine
    container_name: ocoffee-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ocoffee-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocoffee-app
    environment:
      PORT: ${PORT:-3000}
      PG_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./public:/app/public
      - ./app/views:/app/app/views
    networks:
      - ocoffee-network
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.ocoffee.rule=Host(`www.ocoffee.thomas-gambin.com`) || Host(`ocoffee.thomas-gambin.com`)
      - traefik.http.routers.ocoffee.entrypoints=web
      - traefik.http.services.ocoffee.loadbalancer.server.port=3000

volumes:
  postgres_data:

networks:
  ocoffee-network:
    driver: bridge
  proxy:
    external: true